/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locacaobalancim.view;

import DAO.BalancimDAO;
import DAO.ClienteDAO;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import locacaobalancim.controller.SistemaControladora;
import locacaobalancim.model.Balancim;
import locacaobalancim.model.Cliente;
import locacaobalancim.model.Locacao;

/**
 *
 * @author belle
 */
public class LocacaoView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LocacaoView.class.getName());

    /**
     * Creates new form LocacaoView
     */
    public LocacaoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRelTitulo = new javax.swing.JLabel();
        idBal = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dataInicioTxt = new javax.swing.JFormattedTextField();
        dataFinaltxt = new javax.swing.JFormattedTextField();
        CadastrarLocacao = new javax.swing.JButton();
        jLabelRelTitulo1 = new javax.swing.JLabel();

        jLabelRelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRelTitulo.setText("Cadastro de Clientes");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CPF Cliente");

        jLabel2.setText("Numero Identificacao Balancim");

        jLabel3.setText("Data Inicial do aluguel");

        jLabel4.setText("Data Final do aluguel");

        dataInicioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataInicioTxtActionPerformed(evt);
            }
        });

        CadastrarLocacao.setText("Finalizar Locação");
        CadastrarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarLocacaoActionPerformed(evt);
            }
        });

        jLabelRelTitulo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRelTitulo1.setText("Registrar Locação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataFinaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(idBal, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataInicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabelRelTitulo1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(CadastrarLocacao)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabelRelTitulo1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataInicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataFinaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(CadastrarLocacao)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataInicioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataInicioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataInicioTxtActionPerformed

    private void CadastrarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarLocacaoActionPerformed
         try {
        // Supondo que idBal e cpf são campos JTextField
        int idBalancim = Integer.parseInt(idBal.getText());
        String cpfCliente = cpf.getText();

        // Formatar datas
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date dataInicio = sdf.parse(dataInicioTxt.getText());
        Date dataFim = sdf.parse(dataFinaltxt.getText());

        // Buscar os objetos completos
        BalancimDAO balDAO = new BalancimDAO();
        ClienteDAO cliDAO = new ClienteDAO();

        Balancim bal = balDAO.buscarPorIdentificacao(idBalancim); 
        Cliente cli = cliDAO.buscaPorCPF(cpfCliente);            

        if (bal == null || cli == null) {
            JOptionPane.showMessageDialog(this, "Cliente ou Balancim não encontrado.");
            return;
        }

        // Criar locação
        Locacao loc = new Locacao(0, cli, bal, dataInicio, dataFim, 0);

        // Chamar a controladora principal
        SistemaControladora sistema = new SistemaControladora();
        if (sistema.realizarLocacao(loc)) {
            JOptionPane.showMessageDialog(this, "Locação registrada. Valor: R$ " + loc.getValorLocacao());
        } else {
            JOptionPane.showMessageDialog(this, "Balancim indisponível para locação.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar locação: " + e.getMessage());
    }
    }//GEN-LAST:event_CadastrarLocacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LocacaoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarLocacao;
    private javax.swing.JTextField cpf;
    private javax.swing.JFormattedTextField dataFinaltxt;
    private javax.swing.JFormattedTextField dataInicioTxt;
    private javax.swing.JTextField idBal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelRelTitulo;
    private javax.swing.JLabel jLabelRelTitulo1;
    // End of variables declaration//GEN-END:variables
}
