/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locacaobalancim.view;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import locacaobalancim.view.CadastraBalancim;
import locacaobalancim.view.ClienteCadastroView;
import locacaobalancim.view.LocacaoView;

/**
 *
 * @author belle
 */
public class PrincipalView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalView.class.getName());

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
          initComponents();

        setTitle("Sistema de Locação - Menu Principal");
        setSize(400, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        JMenuBar menuBar = new JMenuBar();

        JMenu menuCadastro = new JMenu("Cadastro");
        JMenuItem menuCliente = new JMenuItem("Cliente");
        JMenuItem menuBalancim = new JMenuItem("Balancim");

        JMenu menuLocacao = new JMenu("Locação");
        JMenuItem menuRealizarLocacao = new JMenuItem("Realizar Locação");

        menuCadastro.add(menuCliente);
        menuCadastro.add(menuBalancim);
        menuLocacao.add(menuRealizarLocacao);

        menuBar.add(menuCadastro);
        menuBar.add(menuLocacao);

        setJMenuBar(menuBar);

        // Ações dos menus — abrir as janelas correspondentes
        menuCliente.addActionListener(e -> {
            ClienteCadastroView clienteView = new ClienteCadastroView();
            clienteView.setVisible(true);
        });

        menuBalancim.addActionListener(e -> {
            CadastraBalancim balancimView = new CadastraBalancim();
            balancimView.setVisible(true);
        });

        menuRealizarLocacao.addActionListener(e -> {
            LocacaoView locacaoView = new LocacaoView();
            locacaoView.setVisible(true);
        });
        
        ImageIcon balancimIcon = new ImageIcon(getClass().getResource("/locacaobalancim/view/images.jpg"));
        JLabel labelImagem = new JLabel(balancimIcon, SwingConstants.CENTER);
        
        getContentPane().add(labelImagem);
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRelTitulo = new javax.swing.JLabel();
        javax.swing.JLabel imageLabel = new javax.swing.JLabel();
        jLabelRelTitulo1 = new javax.swing.JLabel();

        jLabelRelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRelTitulo.setText("Cadastro de Balancim");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelRelTitulo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRelTitulo1.setText("Locação de Balancim");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabelRelTitulo1)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabelRelTitulo1)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> {
            new PrincipalView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelRelTitulo;
    private javax.swing.JLabel jLabelRelTitulo1;
    // End of variables declaration//GEN-END:variables
}

